{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: selfheal-postgres-credentials
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}
{{- end }}
